/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CocosDenshion_jsb.ini" on 2013-01-10
* Script version: v0.5
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOSDENSHION

#import "js_bindings_NS_manual.h"

#import "jsfriendapi.h"
#import "js_bindings_config.h"
#import "js_bindings_core.h"
#import "js_bindings_basic_conversions.h"
#import "js_bindings_CocosDenshion_functions.h"


#endif // JSB_INCLUDE_COCOSDENSHION
