/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c cocos2d_jsb.ini" on 2013-01-31
* Script version: v0.5
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOS2D_MAC

#import "js_bindings_cocos2d_classes.h"
JSB_CCDirector_createClass(_cx, cocos2d_mac, "Director");
JSB_CCLayer_createClass(_cx, cocos2d_mac, "Layer");
JSB_CCDirectorMac_createClass(_cx, cocos2d_mac, "DirectorMac");
JSB_CCLayerMultiplex_createClass(_cx, cocos2d_mac, "LayerMultiplex");
JSB_CCLayerRGBA_createClass(_cx, cocos2d_mac, "LayerRGBA");
JSB_CCLayerColor_createClass(_cx, cocos2d_mac, "LayerColor");
JSB_CCLayerGradient_createClass(_cx, cocos2d_mac, "LayerGradient");
JSB_CCMenu_createClass(_cx, cocos2d_mac, "Menu");


#endif // JSB_INCLUDE_COCOS2D_MAC
