/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c chipmunk_jsb.ini" on 2012-09-19
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_CHIPMUNK

#import "js_bindings_chipmunk_manual.h"
JSB_cpConstraint_createClass(_cx, chipmunk, "cpConstraint");
JSB_cpGrooveJoint_createClass(_cx, chipmunk, "cpGrooveJoint");
JSB_cpSimpleMotor_createClass(_cx, chipmunk, "cpSimpleMotor");
JSB_cpPivotJoint_createClass(_cx, chipmunk, "cpPivotJoint");
JSB_cpPinJoint_createClass(_cx, chipmunk, "cpPinJoint");
JSB_cpSlideJoint_createClass(_cx, chipmunk, "cpSlideJoint");
JSB_cpGearJoint_createClass(_cx, chipmunk, "cpGearJoint");
JSB_cpDampedRotarySpring_createClass(_cx, chipmunk, "cpDampedRotarySpring");
JSB_cpDampedSpring_createClass(_cx, chipmunk, "cpDampedSpring");
JSB_cpRatchetJoint_createClass(_cx, chipmunk, "cpRatchetJoint");
JSB_cpRotaryLimitJoint_createClass(_cx, chipmunk, "cpRotaryLimitJoint");
JSB_cpArbiter_createClass(_cx, chipmunk, "cpArbiter");
JSB_cpSpace_createClass(_cx, chipmunk, "cpSpace");
JSB_cpBody_createClass(_cx, chipmunk, "cpBody");
JSB_cpShape_createClass(_cx, chipmunk, "cpShape");
JSB_cpCircleShape_createClass(_cx, chipmunk, "cpCircleShape");
JSB_cpSegmentShape_createClass(_cx, chipmunk, "cpSegmentShape");
JSB_cpBoxShape_createClass(_cx, chipmunk, "cpBoxShape");
JSB_cpPolyShape_createClass(_cx, chipmunk, "cpPolyShape");


#endif // JSB_INCLUDE_CHIPMUNK
