/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CocosBuilderReader_jsb.ini" on 2013-02-09
* Script version: v0.5
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOSBUILDERREADER

#import "js_bindings_NS_manual.h"
#import "CCBReader.h"
#import "CCBAnimationManager.h"
JSB_CCBReader_createClass(_cx, CocosBuilderReader, "_Reader");
JSB_CCBAnimationManager_createClass(_cx, CocosBuilderReader, "AnimationManager");


#endif // JSB_INCLUDE_COCOSBUILDERREADER
