/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c chipmunk_jsb.ini" on 2012-09-19
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_CHIPMUNK

#import "js_bindings_chipmunk_manual.h"
void JSB_cpConstraint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpGrooveJoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpSimpleMotor_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpPivotJoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpPinJoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpSlideJoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpGearJoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpDampedRotarySpring_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpDampedSpring_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpRatchetJoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpRotaryLimitJoint_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpArbiter_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpSpace_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpBody_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpShape_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpCircleShape_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpSegmentShape_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpBoxShape_createClass(JSContext *cx, JSObject* globalObj, const char* name );
void JSB_cpPolyShape_createClass(JSContext *cx, JSObject* globalObj, const char* name );


#endif // JSB_INCLUDE_CHIPMUNK
