/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c cocos2d_jsb.ini" on 2013-02-09
* Script version: v0.5
*/
#import "jsb_config.h"
#ifdef JSB_INCLUDE_COCOS2D_IOS

#import "jsb_cocos2d_classes.h"


#endif // JSB_INCLUDE_COCOS2D_IOS
