/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CocosBuilderReader_jsb.ini" on 2013-02-15
* Script version: v0.6
*/
#import "jsb_config.h"
#if JSB_INCLUDE_COCOSBUILDERREADER

#import "jsb_NS_manual.h"
#import "CCBReader.h"
#import "CCBAnimationManager.h"
JSB_CCBReader_createClass(_cx, CocosBuilderReader, "_Reader");
JSB_CCBAnimationManager_createClass(_cx, CocosBuilderReader, "AnimationManager");


#endif // JSB_INCLUDE_COCOSBUILDERREADER
