/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CocosDenshion_jsb.ini" on 2013-02-09
* Script version: v0.5
*/
#import "jsb_config.h"
#ifdef JSB_INCLUDE_COCOSDENSHION

#import "jsb_NS_manual.h"

#import "jsfriendapi.h"
#import "jsb_config.h"
#import "jsb_core.h"
#import "jsb_basic_conversions.h"
#import "jsb_CocosDenshion_functions.h"


#endif // JSB_INCLUDE_COCOSDENSHION
