/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CocosDenshion_jsb.ini" on 2013-02-09
* Script version: v0.5
*/
#import "jsb_config.h"
#ifdef JSB_INCLUDE_COCOSDENSHION

#import "jsb_NS_manual.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif


#endif // JSB_INCLUDE_COCOSDENSHION
