/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c system_jsb.ini" on 2013-02-09
* Script version: v0.5
*/
#include "jsb_config.h"
#ifdef JSB_INCLUDE_SYSTEM

#include "LocalStorage.h"

#ifdef __cplusplus
extern "C" {
#endif
JSBool JSB_localStorageGetItem(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_localStorageRemoveItem(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_localStorageSetItem(JSContext *cx, uint32_t argc, jsval *vp);

#ifdef __cplusplus
}
#endif


#endif // JSB_INCLUDE_SYSTEM
